[package]
name = "openbands_miniapp"
type = "bin"
authors = ["masaun"]
compiler_version = ">=1.0.0"
version = "0.1.0"

[dependencies]
jwt = { tag = "saleel/deps-update-beta11", git = "https://github.com/zkemail/noir-jwt" }  # PR.15 of the noir-jwt repo, which is supposed to work with the Noir/Nargo v1.0.0-beta.11
#jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }   # For Noir and Nargo >= v1.0.0-beta.5 / bb.js <= v0.85.0 compatibility
#jwt = { tag = "v0.4.4", git = "https://github.com/zkemail/noir-jwt" }   # For Noir and Nargo <= v1.0.0-beta.3 / bb.js <= v0.84.0 compatibility